FROM devdocker.mulesoft.com:18078/base/node:6.9-1.5.0-2-ge901d36

# Install packages
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        git \
        openssh-client

# Folder to copy source to be built
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
